Algoritmul lui Boruvka pentru APCM
roalgo-discord/arhiva-educationala pull request #36
Opened 2024-10-11 13:40 UTC by TraianDanciu

2024-10-11 14:14 UTC, stefdasca requested changes
e bine, dar modifica te rog unde ai zis, also trece-te autor (sau cel mai simplu, trece-ne pe amandoi autori)

2024-10-11 14:14 UTC, stefdasca commented on docs/mediu/apcm.md
> +Aici puteți găsi o implementare în C++ a algoritmului lui Boruvka:
As pune o observatie pentru cazul cand ai raspunsul impossible (eu unul am facut asta cu un bool in care verific daca am adaugat o muchie in pasul curent, dar ma gandesc ca pot fi si alte variante, poate sa verifici daca graful e conex daca tot ai DSU deja?)

2024-10-11 14:14 UTC, stefdasca commented on docs/mediu/apcm.md
> +Aici puteți găsi o implementare în C++ a algoritmului lui Boruvka:
https://cses.fi/paste/2a09f78601388a1fa5047b/

2024-10-11 14:14 UTC, stefdasca commented on docs/mediu/apcm.md
> +Niciunul dintre algoritmi nu este mai bun mereu decât celălalt, mai puțin în cazurile particulare în care funcționează doar algoritmul lui Boruvka. Pe de o parte, Kruskal se dovedește a fi mult mai b
cazuri precum? adica din ce vad, kruskal e m log m si boruvka e m log n dar boruvka pare mai dificil de scris. ar merge aici un exemplu sau ceva in care boruvka sa dea outperform clar la kruskal

2024-10-11 14:14 UTC, stefdasca commented on docs/mediu/apcm.md
> +* [Boruvka's Algorithm](https://codeforces.com/blog/entry/77760)
aici recunosc ca m-ai facut sa inteleg algoritmul dat fiind ca nu l-am implementat niciodata, well done :)

2024-10-11 14:14 UTC, stefdasca commented on docs/mediu/apcm.md
> +* [Boruvka's Algorithm](https://codeforces.com/blog/entry/77760)
nu e asa avansat cum credeam

2024-10-11 14:14 UTC, stefdasca commented on docs/mediu/apcm.md
> +Niciunul dintre algoritmi nu este mai bun mereu decât celălalt, mai puțin în cazurile particulare în care funcționează doar algoritmul lui Boruvka. Pe de o parte, Kruskal se dovedește a fi mult mai b
sau poate o problema in care boruvka bate ceilalti algoritmi

2024-10-11 17:10 UTC, TraianDanciu commented on docs/mediu/apcm.md
> +    Acest algoritm începe cu fiecare nod fiind într-o comopnentă conexă doar cu el însuși. Apoi, va face iterații prin graf, până când nu este arbore (adică cât timp mai sunt cel puțin două component
Da, am zis asa fiind ca in unele probleme difera comparatia costurilor

2024-10-12 15:34 UTC, stefdasca requested changes
repara typoul si dupa dau push

2024-10-12 15:34 UTC, stefdasca commented on docs/mediu/apcm.md
> +    Acest algoritm începe cu fiecare nod fiind într-o comopnentă conexă doar cu el însuși. Apoi, va face iterații prin graf, până când nu este arbore (adică cât timp mai sunt cel puțin două component
mic typo aici iar

2024-10-12 15:42 UTC, stefdasca approved these changes

2024-10-12 15:42 UTC, merged