HLD
roalgo-discord/arhiva-educationala pull request #49
Opened 2024-10-24 11:23 UTC by RaulArdelean18

As dori sa vad opinia altora despre ce am scris pana acuma, daca mai trebuie sa adaug sau sa modific ceva. Mai am in plan sa adaug HLD + lazy propagation.

2024-10-26 22:55 UTC, stefdasca requested changes

2024-10-26 22:55 UTC, stefdasca commented
E un inceput bun, dar mai trebuie adaugate chestii

2024-10-27 08:55 UTC, RaulArdelean18 commented
Am modificat, acuma nu stiu ce sa mai scriu la concluzie

2024-10-28 14:37 UTC, stefdasca approved these changes

2024-10-28 14:37 UTC, merged