modified from latex to markdown
roalgo-discord/arhiva-educationala pull request #5
Opened 2024-06-22 12:38 UTC by RaduMocanasu

2024-06-26 02:19 UTC, overanalytcl requested changes
Ai putea să reformatezi codul folosind stilul Google? (se aplică la toate exemplele)
Excepția de la stil e că folosim indentare de 4 în loc de indentare de 2.

P.S. nu te ajută deloc să pui spații înainte de/după < sau >.

2024-06-27 05:26 UTC, overanalytcl approved these changes
Cu toate acestea fiind zise, LGTM.

@stefdasca Ce părere ai?

2024-06-27 05:26 UTC, overanalytcl commented on docs/mediu/sortare_topologica.md
> +    // Citire
Asta e puțin redundant, dar se putea și mai rău.

2024-06-27 05:26 UTC, overanalytcl commented on docs/mediu/sortare_topologica.md
> +    for (auto e : edges) {
Se putea `const auto&` aici, dar trecem cu vederea acum.

2024-06-27 07:42 UTC, stefdasca approved these changes
Arata foarte bine, cred ca un alt aspect despre care ai mai fi putut vorbi e sortarea topologica minim lexicografica dar aici e pur si simplu vorba de folosirea unui priority queue, iar in ceea ce priveste dinamicile ce tin de sortarea topologica, va trebui sa abordam subiectul cand vom scrie la dinamici.

La sortarea topologica se poate folosi si BFS dar din nou putem adauga chestii pe parcurs, ideea principala e potrivita.

2024-06-27 08:04 UTC, merged