Update functions.md
roalgo-discord/arhiva-educationala pull request #58
Opened 2024-10-31 10:05 UTC by Secret-chest

2024-10-31 19:41 UTC, stefdasca requested changes

2024-10-31 19:41 UTC, stefdasca commented on docs/cppintro/functions.md
> +    În momentul în care scriem o instrucțiune de tip _return_, funcția se va opri și în cazul funcțiilor non-void, va returna valoarea dată.
de acord ca trebuie schimbata un pic exprimarea, poate poti spune ca o alta observatie ca un asemenea exemplu e atunci cand punem return 0 in main, se termina de rulat programul?

2025-01-09 12:04 UTC, pascalecu commented
De la mine LGTM

2025-01-17 13:01 UTC, pascalecu commented
Închid acest PR. Am integrat toate schimbările (cu excepția lui sumcif; consider că factorialul este destul de bun ca exemplu, dar voi revizita asta în viitor).

2025-01-17 13:01 UTC, closed without merging