Red-Black Tree
roalgo-discord/arhiva-educationala pull request #60
Opened 2024-10-31 10:22 UTC by sSlepa

Adaugare parte teorie Arbori Red-Black.

2024-10-31 19:49 UTC, stefdasca requested changes
ai uitat sa pui intre $ destule notatii matematice, also mai sunt inconsistente la format pe care trebuie sa le repari.

2024-10-31 19:49 UTC, stefdasca commented on docs/dificil/redblacktree.md
> +6) Un Arbore Red-Black cu N noduri are înălțimea maximă 2 * $\log (N)$.
``$2 \cdot \log N$ ``

2024-10-31 19:49 UTC, stefdasca commented on docs/dificil/redblacktree.md
> +- Dacă ambii fii a-i fratelui sunt ${\color{grey}Black}$ atunci îl recolorăm și urcăm în părintele lui X.
fii ai fratelui*, also virgula inainte de atunci

2024-10-31 19:49 UTC, stefdasca commented on docs/dificil/redblacktree.md
> +- Complexitatea operației de delete în Worst Case $O(2 * log(N))$ dar constanta o putem anula.
la fel aici cu cdot in loc de steluta

2024-10-31 19:54 UTC, sSlepa commented
repar, adaug probleme si dau iar push

2025-02-26 23:37 UTC, pascalecu commented
Din moment ce @stefdasca nu s-a mai uitat și s-au schimbat multe pe repo de atunci, voi închide PR-ul și integrez separat articolul.

2025-02-26 23:37 UTC, closed without merging